name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Run setup.sh
        run: ./setup.sh

      - name: Build
        run: make build
