---
name: module3_task2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  builds:

    name: first job

    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"  # Download code from the repository
        uses: actions/checkout@v3
      - name: "Run bash script"
        run: cd module3_task2 && ./setup.sh
      - name: "Run make build"  # Execute the command make build
        run: cd module3_task2 && make build
      - name: "Testing"
        run: |
          cd module3_task2 && make validate
          make integration-tests
          make unit-tests
          make package
          make clean
      - name: "archive build"
        uses: actions/upload-artifact@v3
        with:
          name: "upload package"
          path: module3_task2/awesome-website.zip
  
