name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs once per day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment
        run: ./setup.sh

      - name: Build
        run: make build
