name: module3_task2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Build and test
        run: make build test

      - name: Package
        run: make package

      - name: Archive package
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: awesome-website.zip
