- Customize the content of DEPLOY.md based on your project's specific details and requirements.
- Save DEPLOY.md.

Step 3: Create a new workflow (module3_task2)
- Create a new file named module3_task2.yml in the .github/workflows/ directory of your project.
- Open module3_task2.yml and add the following contents:
```yaml
name: module3_task2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and test
        run: make lint test

      - name: Package
        run: make package

      - name: Archive package
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: awesome-website.zip
