---
name: module3_task0

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  builds:

    name: first job

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate Makefile execution make help command
        run: make help
        working-directory: module3_task0

l