name: Module 3 Task 1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install make golang -y
          chmod +x setup.sh
          ./setup.sh

      - name: Build the project
        run: make build
